name: Cross-compile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - debian

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armel, armhf, i386]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install necessary build files
        run: sudo apt-get update && sudo apt-get install -y libssl-dev libcrypto++-dev zlib1g-dev libcurl4-openssl-dev libcjson-dev

      - name: Install cross-compilation tools
        run: sudo apt-get install -y gcc-${{ matrix.arch }}-linux-gnu g++-${{ matrix.arch }}-linux-gnu

      - name: Build Debian package
        env:
          DEB_BUILD_OPTIONS: nocheck
          DEB_HOST_ARCH: ${{ matrix.arch }}
          CC: ${{ matrix.arch }}-linux-gnu-gcc
          CXX: ${{ matrix.arch }}-linux-gnu-g++
        run: |
          sudo apt-get install -y devscripts
          debuild -us -uc -ui --host-arch=${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chatgpt_${{ matrix.arch }}.deb
          path: ../chatgpt_*_${{ matrix.arch }}.deb