name: Cross-compile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - debian

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armel, armhf, i386]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install necessary build files
        run: sudo apt-get install -y libssl-dev libcrypto++-dev zlib1g-dev libcurl4-openssl-dev libcjson-dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: false

      - name: Set up Docker container
        run: |
          docker create --name deb-builder -v $(pwd):/src debian:buster-slim
          docker cp deb-builder:/src/debian .

      - name: Build Debian package
        run: |
          sudo apt-get install -y devscripts
          debuild -us -uc -ui --host-arch=${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chatgpt_${{ matrix.arch }}.deb
          path: ../chatgpt_*_${{ matrix.arch }}.deb