name: Cross-compile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - workflow-test

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armel, armhf, i386]
        dockcross_image: ['linux-x64', 'linux-arm64', 'linux-armel', 'linux-armhf', 'linux-x86']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build custom dockcross image
        run: docker build -t custom-dockcross -f Dockerfile.crosscompile .
      
      - name: Install dockcross script
        run: docker run --rm custom-dockcross > dockcross && chmod +x dockcross

      - name: Configure and build
        run: |
          export CROSS_HOST_ARCH="${{ matrix.arch }}"
          export DOCKCROSS_IMAGE_TAG="${{ matrix.dockcross_image }}"
          ./dockcross bash -c "export CC=${CROSS_HOST_ARCH}-linux-gnu-gcc && export CXX=${CROSS_HOST_ARCH}-linux-gnu-g++ && ./configure --host=${CROSS_HOST_ARCH}-linux-gnu && make"

      - name: Create DEB package
        run: |
          sudo apt-get install -y devscripts
          debuild -us -uc -ui

      - name: Copy DEB package to deb_output folder
        run: |
          mkdir -p deb_output
          cd ..
          cp *.deb chatgpt-term/deb_output/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chatgpt_${{ matrix.arch }}.deb
          path: deb_output/chatgpt_*_${{ matrix.arch }}.deb