name: Cross-compile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - debian

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armel, armhf, i386]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: myrepo/myimage:${{ matrix.arch }}

      - name: Configure and Cross-compile
        run: |
          docker run --rm \
            -v $(pwd):/src \
            -e ARCH=${{ matrix.arch }} \
            myrepo/myimage:${{ matrix.arch }} \
            "sh -c './configure --host=$ARCH-linux-gnueabihf- && make'"

      - name: Build Debian package
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts
          debuild -us -uc -ui

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chatgpt_${{ matrix.arch }}.deb
          path: ../chatgpt_*_${{ matrix.arch }}.deb
