name: Cross-compile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - workflow-test

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            dockcross_image: dockcross/linux-x64
          - arch: arm64
            dockcross_image: dockcross/linux-arm64
          - arch: armel
            dockcross_image: dockcross/linux-armv5
          - arch: armhf
            dockcross_image: dockcross/linux-armv7
          - arch: i386
            dockcross_image: dockcross/linux-x86
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Dockcross image
        run: docker pull ${{ matrix.dockcross_image }}

      - name: Create Dockcross script
        run: |
          docker run --rm ${{ matrix.dockcross_image }} > ./dockcross
          chmod +x ./dockcross

      - name: Install dependencies
        run: ./dockcross bash -c "apt-get update && apt-get install -y libssl-dev libcrypto++-dev zlib1g-dev libcurl4-openssl-dev libcjson-dev

      - name: Configure and build
        run: |
          ./dockcross bash -c "./configure --host=${{ matrix.arch }} && make"

      - name: Create DEB package
        run: ./dockcross bash -c "sudo apt-get install -y devscripts && debuild -us -uc -ui"

      - name: Copy DEB package to deb_output folder
        run: |
          mkdir -p deb_output
          cd ..
          cp *.deb chatgpt-term/deb_output/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chatgpt_${{ matrix.arch }}.deb
          path: deb_output/chatgpt_*_${{ matrix.arch }}.deb
