name: Cross-compile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - workflow-test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64, amd64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    - name: Cross-compile package
      run: |
        docker buildx build --platform linux/$arch -t my-package .
        docker create --name my-container my-package
        docker start my-container
        PACKAGE_NAME=$(dpkg-parsechangelog | awk '/^Source:/ { print $2 }')
        PACKAGE_VERSION=$(dpkg-parsechangelog | awk '/^Version:/ { print $2 }')
        docker exec -w /app my-container dpkg-buildpackage -us -uc
        docker cp my-container:/app/${PACKAGE_NAME}_${PACKAGE_VERSION}_${arch}.deb .
        docker stop my-container
        docker rm my-container
      env:
        arch: ${{ matrix.arch }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_${{ matrix.arch }}.deb
        path: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_${{ matrix.arch }}.deb